### ISSUE TITLE
State 'foo' is already defined - angular@2.4.x

### ISSUE THREAD

**Issue by jspizziri** [ui-router/ng2#42] opened 2017-02-08 21:00 UTC
This is a duplicate issue of https://github.com/angular-ui/ui-router/issues/3326, as I wasn't sure where the appropriate place to file it was. Upon upgrading my app to `angular@2.4.x` I started receiving a duplicate state declaration error in the following situation.

If I have two modules:

```ts
//app/foo/foo.module.ts
import { NgModule } from '@angular/core';
import { UIRouterModule } from 'ui-router-ng2';

import FooComponent from './foo.component';

@NgModule({
  imports:      [
    UIRouterModule.forChild({ states: [
      {
        name: 'foo',
        url: '/foo',
        component: FooComponent
      }
    ]),
  ],
  declarations: [],
  exports: [],
  providers: [],
})
export default class FooModule { }
```

```ts
//app/bar/bar.module.ts
import { NgModule } from '@angular/core';
import { UIRouterModule } from 'ui-router-ng2';

import FooModule from '../foo/foo.module';
import BarComponent from './bar.component';

@NgModule({
  imports:      [
    UIRouterModule.forChild({ states: [
      {
        name: 'bar',
        url: '/bar',
        component: BarComponent
      }
    ]),

    FooModule,
  ],
  declarations: [],
  exports: [],
  providers: [],
})
export default class BarModule { }
```

In this case I receive a runtime error stating `State 'foo' is already defined`, as a result of adding `FooModule` to the list of imports in `BarModule`. I'm not sure if this is intended behavior, however this is not how the router behaves in `angular@2.1.x`

**Comment by christopherthielen** [comment] 2017-02-08 21:03
Can you post your root module too?

**Comment by jspizziri** [comment] 2017-02-08 21:09
```ts
//app/app.module.ts

import { LocationStrategy, PathLocationStrategy, Location } from '@angular/common';
import { SystemJsNgModuleLoader, NgModuleFactoryLoader, NgModule, ErrorHandler } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { UIRouterModule, UIRouter } from 'ui-router-ng2';

import FooModule from './foo/foo.module';
import BarModule from './bar/bar.module';
import AppComponent from './app.component';

@NgModule({
  imports: [
    BrowserModule,
    UIRouterModule.forRoot({
      useHash: false,
      config: function uiRouterConfigFn(router: UIRouter) {
        router.urlService.rules.otherwise({ state: 'foo' });
        router.stateRegistry.root();
      },
    }),

    FooModule,
    BarModule,
  ],
  declarations: [ AppComponent ],
  bootstrap: [ AppComponent ],
  providers: [
    { provide: LocationStrategy, useClass: PathLocationStrategy },
    { provide: NgModuleFactoryLoader, useClass: SystemJsNgModuleLoader },
    { provide: Location, useClass: Location },
  ],
})
export class AppModule {}
```

**Comment by christopherthielen** [comment] 2017-02-08 21:12
OK, that's interesting. 
What happens if you change your root module imports to:

```js
  imports: [
    BrowserModule,
    UIRouterModule.forRoot({
      useHash: false,
      config: function uiRouterConfigFn(router: UIRouter) {
        router.urlService.rules.otherwise({ state: 'foo' });
        router.stateRegistry.root();
      },
    }),

    BarModule,
  ],
```

**Comment by jspizziri** [comment] 2017-02-08 22:50
Thanks for looking into this!

That does make the error go away, however I'd prefer to not have to do that long term as `FooModule` also contains functionality which is used by a couple of other modules (e.g. a form or something) If I import `FooModule` into more than one other module (let's say `FooBarModule` uses the `FooComponent`) then the duplicate state error occurs again. 

The option of moving the reusable forms into a `SharedModule` is also not really appealing as I would basically just end up with a giant `SharedModule` with a other modules effectively only representing views of the application, which would effectively result in a flat app structure.

**Comment by christopherthielen** [comment] 2017-02-09 13:16
Agreed, this is a bug that needs to be fixed

**Comment by christopherthielen** [comment] 2017-02-09 14:19
I'm unable to reproduce this error.  Can you please reproduce it for me? 

I've got an angular-cli project started here: https://github.com/christopherthielen/foo-is-already-defined

Run `ng serve`

**Comment by jspizziri** [comment] 2017-02-10 14:57
I'll try to get a working repo for you this weekend.

**Comment by aeternusrahl** [comment] 2017-02-15 14:48
I believe this is related to this angular issue: https://github.com/angular/angular/issues/13652

**Comment by christopherthielen** [comment] 2017-02-17 16:44
Thanks for posting that. I think we can work around the bug by eliminating duplicates when applying the ng module configs

**Comment by christopherthielen** [comment] 2017-03-05 19:11
@jspizziri I think I have a fix for this, but I can't test it without a reproduction.  I'm going to push the change, and when I do will close the issue.  If it's not fixed we can reopen.

**Comment by jspizziri** [comment] 2017-03-05 19:26
@christopherthielen,

Thanks for working on this! Sorry I wasn't able to get you a reproduction. Once the fix is pushed, I'll make sure to let you know if it does or does not fix the issue in our repository.

Thanks again!

**Closed** 2017-03-05 19:29 UTC
Labels: bug
